//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;


namespace BankDesktop.Model.EF
{
    public class SkContext : DbContext
    {
        public SkContext(string connectionString) : base(connectionString)
        {
        }

        public DbSet<Clients> Clients { get; set; }
        public DbSet<Types> ClientTypes { get; set; }
        public DbSet<BankAccounts> BankAccounts { get; set; }
        public DbSet<BankCredits> BankCredits { get; set; }
    }
}
